// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories;

#nullable disable

namespace Repositories.Migrations
{
    [DbContext(typeof(TestDbContext))]
    partial class TestDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.Entity.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Darnell Brekke"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Lynda Lueilwitz"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Vickie Beier"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Kristy Kozey"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Emmett Howe"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Johnathan Pfeffer"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Jacob Crooks"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Irving Padberg"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Johnny Ryan"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Darnell Erdman"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Lillian Kemmer"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Carol Muller"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Lawrence Bahringer"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Amanda Roberts"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Fernando Murray"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Deanna Harvey"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Ida Nolan"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Nick Senger"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Jesus Johnson"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Alyssa Roob"
                        });
                });

            modelBuilder.Entity("Domain.Entity.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Domain.Entity.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tasty Soft Shirt"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Licensed Soft Shoes"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ergonomic Rubber Keyboard"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Practical Concrete Chips"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Handmade Wooden Chair"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Tasty Plastic Towels"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Intelligent Soft Computer"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Generic Concrete Salad"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Fantastic Plastic Towels"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Ergonomic Fresh Hat"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Rustic Soft Pants"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Ergonomic Fresh Ball"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Licensed Soft Computer"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Awesome Fresh Cheese"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Licensed Soft Salad"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Generic Concrete Gloves"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Rustic Granite Sausages"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Handmade Granite Fish"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Fantastic Metal Gloves"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Intelligent Cotton Shoes"
                        });
                });

            modelBuilder.Entity("Domain.Entity.RandomNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("Numbers");
                });

            modelBuilder.Entity("Domain.Entity.Order", b =>
                {
                    b.HasOne("Domain.Entity.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Domain.Entity.Customer", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
